### ISSUE TITLE
alias searchfield should be case insensitiv

### ISSUE THREAD

**Issue by kkrebs** [MyCoRe-Org/mir-alias-plugin#5]
You should add LowerCaseFilterFactory

        "filters": [
          {
            "class": "solr.LowerCaseFilterFactory"
          }
        ]

**Comment by kkrebs** [comment]
I changed my solr-schema.json this way:
```
[
  {
    "add-field-type": {
      "name": "mir.alias.string_ci",
      "class": "solr.TextField",
      "analyzer": {
        "tokenizer": {
          "class": "solr.KeywordTokenizerFactory"
        },
        "filters": [
          {
            "class": "solr.LowerCaseFilterFactory"
          }
        ]
      }
    }
  },
  {
    "add-field": {
        "name": "alias",
        "type": "mir.alias.string_ci",
        "indexed": true,
        "stored": true,
        "multiValued": false
    }
  }
]
```

And now both variants work:
https://reposis-test.gbv.de/repper/publikationen/friedrich300-colloquien/Friedrich-Dynastie/
https://reposis-test.gbv.de/repper/publikationen/friedrich300-colloquien/friedrich-dynastie/

**Comment by rochpaul** [comment]
Case sensitive type of solr alias field is comitted into master.
https://github.com/MyCoRe-Org/mir-alias-plugin/commit/7a8989fecf03e825210835f4e4a512a8e1563a89
